export const data = [
  {
    title: 'Wecare',
    desc: 'lorem ipsom dolors semete...',
    code: 'https://github.com/DineshRout779/old-frontend-projects/tree/main/Wecare',
    live: '/Wecare/index.html',
    img: '/assets/wecare.png',
  },
  {
    title: 'Testimonials Challange',
    desc: 'lorem ipsom dolors semete...',
    code: 'https://github.com/DineshRout779/old-frontend-projects/tree/main/Challange-Testimonials-grid-section',
    live: 'Challange-Testimonials-grid-section/index.html',
    img: '/assets/project-2.png',
  },
  {
    title: 'Restaurant Website',
    desc: 'lorem ipsom dolors semete...',
    code: 'https://github.com/DineshRout779/old-frontend-projects/tree/main/Food-website',
    live: '/Food-website/index.html',
    img: '/assets/food.png',
  },
  {
    title: 'Huddle landing page 1',
    desc: 'lorem ipsom dolors semete...',
    code: 'https://github.com/DineshRout779/old-frontend-projects/tree/main/Huddle-landing-page-with-curved-sections-challenge',
    live: '/Huddle-landing-page-with-curved-sections-challenge/index.html',
    img: '/assets/hurdle1.png',
  },
  {
    title: 'Huddle landing page 2',
    desc: 'lorem ipsom dolors semete...',
    code: 'https://github.com/DineshRout779/old-frontend-projects/tree/main/Hurdle-Landing-Page',
    live: '/Hurdle-Landing-Page/index.html',
    img: '/assets/hurdle2.png',
  },
  {
    title: 'Profile card challenge',
    desc: 'lorem ipsom dolors semete...',
    code: 'https://github.com/DineshRout779/old-frontend-projects/tree/main/Profile_card_challenge',
    live: '/Profile_card_challenge/index.html',
    img: '/assets/profile.png',
  },
  {
    title: 'Random Quotes Generator',
    desc: 'lorem ipsom dolors semete...',
    code: 'https://github.com/DineshRout779/old-frontend-projects/tree/main/Random-Quotes-Generator',
    live: '/Random-Quotes-Generator/index.html',
    img: '/assets/quote.png',
  },
  {
    title: 'Room Homepage Challange',
    desc: 'lorem ipsom dolors semete...',
    code: 'https://github.com/DineshRout779/old-frontend-projects/tree/main/Room_Homepage_Challange',
    live: '/Room_Homepage_Challange/index.html',
    img: '/assets/room.png',
  },
  {
    title: 'Social proof challange',
    desc: 'lorem ipsom dolors semete...',
    code: 'https://github.com/DineshRout779/old-frontend-projects/tree/main/Social-proof',
    live: '/Social-proof/index.html',
    img: '/assets/social.png',
  },
  {
    title: 'Testimonial page',
    desc: 'lorem ipsom dolors semete...',
    code: 'https://github.com/DineshRout779/old-frontend-projects/tree/main/Testimonial-page',
    live: '/Testimonial-page/index.html',
    img: '/assets/testimonials.png',
  },
  {
    title: 'The Band Landing page',
    desc: 'lorem ipsom dolors semete...',
    code: 'https://github.com/DineshRout779/old-frontend-projects/tree/main/The_Band',
    live: '/The_Band/index.html',
    img: '/assets/band.png',
  },
];
